/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-ZO6Cp-kMkjNuAW3gqoCPTSNryAZBW1l52hnnicS82O06KshyPx8quZmY1RAClc6qTf227yOA6-WRBsBwb5vxUKmeI8v-5SqLEuNTcxDdN6dZ-K5okLzfZnfA",
  "tt": "tt-1-gxFN71N6KBUCO1OA1UKjFuId-Ym9xZp8gPSl35fmRYU=",
  "version": "2020-11-20"
}

export default ebconfig;